"use client";

import { useTasks } from "@/lib/hooks";
import Card, { CardHeader } from "@/components/Card";
import StatusBadge from "@/components/StatusBadge";
import RoleBadge from "@/components/RoleBadge";
import TimeAgo from "@/components/TimeAgo";
import EmptyState from "@/components/EmptyState";
import { ListTodo, Loader2, Play, Code, Palette, Search, FileCheck, BarChart3, FileText } from "lucide-react";
import { api } from "@/lib/api";
import { useState } from "react";
import type { Task } from "@/lib/types";

const TYPE_ICONS: Record<string, React.ElementType> = {
  code: Code,
  design: Palette,
  research: Search,
  review: FileCheck,
  analysis: BarChart3,
  document: FileText,
};

function TaskRow({ task }: { task: Task }) {
  const [executing, setExecuting] = useState(false);
  const TypeIcon = TYPE_ICONS[task.task_type] || FileText;

  const handleExecute = async () => {
    setExecuting(true);
    try {
      await api.executeTask(task.id);
    } catch {
      // silently handled
    }
    setExecuting(false);
  };

  const canExecute = task.status === "pending" || task.status === "failed";

  return (
    <div
      className="flex items-center gap-4 rounded-lg p-4 transition-colors"
      style={{ background: "var(--bg-surface-raised)", border: "1px solid var(--border-subtle)" }}
    >
      <div
        className="flex h-9 w-9 items-center justify-center rounded-lg shrink-0"
        style={{ background: "var(--accent-dim)" }}
      >
        <TypeIcon size={16} style={{ color: "var(--accent)" }} />
      </div>

      <div className="flex-1 min-w-0">
        <div className="flex items-center gap-2 mb-1">
          <span className="text-sm font-medium truncate" style={{ color: "var(--text-primary)" }}>
            {task.title}
          </span>
          <span className="text-[10px] font-mono px-1.5 py-0.5 rounded"
            style={{ background: "var(--bg-surface)", color: "var(--text-muted)" }}
          >
            {task.task_type}
          </span>
        </div>
        <p className="text-xs truncate" style={{ color: "var(--text-muted)" }}>
          {task.description}
        </p>
        <div className="flex items-center gap-3 mt-2">
          <RoleBadge role={task.agent_role} />
          <span className="text-[10px] font-mono px-1.5 py-0.5 rounded"
            style={{ background: "var(--bg-surface)", color: "var(--text-muted)" }}
          >
            {task.source}
          </span>
        </div>
      </div>

      <div className="flex items-center gap-3 shrink-0">
        <StatusBadge status={task.status} />
        <TimeAgo date={task.created_at} />
        {canExecute && (
          <button
            onClick={handleExecute}
            disabled={executing}
            className="flex items-center gap-1 rounded-lg px-2.5 py-1.5 text-[11px] font-medium transition-opacity cursor-pointer disabled:opacity-50"
            style={{ background: "var(--accent-dim)", color: "var(--accent)" }}
          >
            {executing ? <Loader2 size={12} className="animate-spin" /> : <Play size={12} />}
            Execute
          </button>
        )}
      </div>
    </div>
  );
}

export default function TasksPage() {
  const { data: tasks, isLoading } = useTasks();
  const [filter, setFilter] = useState<string>("all");

  const filteredTasks = tasks?.filter((t) => {
    if (filter === "all") return true;
    return t.status === filter;
  });

  const statusCounts = tasks?.reduce(
    (acc, t) => {
      acc[t.status] = (acc[t.status] || 0) + 1;
      return acc;
    },
    {} as Record<string, number>,
  ) ?? {};

  return (
    <div className="max-w-5xl mx-auto">
      <div className="mb-8 animate-fade-in">
        <h1 className="text-xl font-bold" style={{ color: "var(--text-primary)" }}>
          Tasks
        </h1>
        <p className="text-sm mt-1" style={{ color: "var(--text-muted)" }}>
          Track and execute tasks generated by meetings or created directly
        </p>
      </div>

      {/* Status filter pills */}
      <div className="flex items-center gap-2 mb-6">
        {["all", "pending", "running", "completed", "failed"].map((s) => (
          <button
            key={s}
            onClick={() => setFilter(s)}
            className="rounded-full px-3 py-1.5 text-[11px] font-medium transition-colors cursor-pointer"
            style={{
              background: filter === s ? "var(--accent-dim)" : "var(--bg-surface)",
              color: filter === s ? "var(--accent)" : "var(--text-muted)",
              border: `1px solid ${filter === s ? "rgba(212,168,83,0.3)" : "var(--border)"}`,
              fontFamily: "var(--font-mono)",
            }}
          >
            {s === "all" ? `All (${tasks?.length ?? 0})` : `${s} (${statusCounts[s] || 0})`}
          </button>
        ))}
      </div>

      {isLoading && (
        <div className="flex items-center justify-center h-[40vh]">
          <Loader2 className="animate-spin" size={24} style={{ color: "var(--text-muted)" }} />
        </div>
      )}

      {!isLoading && (!filteredTasks || filteredTasks.length === 0) && (
        <Card>
          <EmptyState icon={<ListTodo size={32} />} message="No tasks found." />
        </Card>
      )}

      <div className="flex flex-col gap-3">
        {filteredTasks?.map((task, i) => (
          <div key={task.id} className="animate-fade-in" style={{ animationDelay: `${i * 30}ms` }}>
            <TaskRow task={task} />
          </div>
        ))}
      </div>
    </div>
  );
}
